Treat messages where fatal is set to null as 'info'
vfile/vfile-statistics pull request #3
Opened 2017-07-12 05:12 UTC by brendo

Related to https://github.com/vfile/vfile/pull/18, in fact the test can be cleaned up a little once `isFatal` can be set through the message constructor.

2017-07-12 18:22 UTC, wooorm requested changes

2017-07-12 18:22 UTC, wooorm commented on index.js
> +  return {fatal: result.true, nonfatal: result.false, info: result.null, total: total};
How about adding `'warn'` too? And using nonfatal as all values that are not `fatal: true` (the current behaviour)?

2017-07-12 18:22 UTC, wooorm commented on index.js
> +        result[value[index].fatal]++;
`fatal: undefined` should be treated as `null` / `info`

2017-07-12 18:22 UTC, wooorm commented on readme.md
> +Count [vfile][] messages per category (fatal, nonfatal, info and total).
and `warn`

2017-07-12 18:22 UTC, wooorm commented on readme.md
> +{ fatal: 1, nonfatal: 2, info: 0, total: 3 }
and `warn`, and could you add an info message so it counts as `info: 1`?

2017-07-13 00:31 UTC, brendo commented
I've made changes based of your review. The readme example could be a cleaned up a little (and the test) once `.info` is available on vfile. Happy to do that once that happens 👍

2017-07-17 14:29 UTC, wooorm approved these changes

2017-07-17 14:38 UTC, closed without merging

2017-07-17 14:44 UTC, wooorm commented
I refactored it a bit, but don’t take that personally. Thanks a lot for working on this! 🎉